### ISSUE TITLE
Name annotations vs arbitrary identifiers

### ISSUE THREAD

**Issue by AndrewScheidecker** [WebAssembly/annotations#1]
While I think this kind of metadata could be useful for stuff like the host bindings, I don't think it's a good solution to the [arbitrary names issue](https://github.com/WebAssembly/spec/issues/617). Consider:

```
(module
  (func $lambda (@name "λ") ...)
  ... (call $lambda) ...
)
```

What should this "disassemble" to? You would need to add a way to store both names for `$lambda` in the name section, and for producers to produce something useful for both names. Otherwise you're going to end up with something like this:

```
(module
  (func $0 (@name "λ") ...)
  ... (call $0) ...
)
```

I think it's simpler to extend the identifier syntax to support arbitrary strings (as discussed [in the original issue](https://github.com/WebAssembly/spec/issues/617)):

```
(module
  (func $"λ" ...)
  ... (call $"λ") ...
)
```

**Comment by tlively** [comment]
The discussion about this idea ended up being held on #21, so this can probably be closed.

**Comment by rossberg** [comment]
Closing as duplicate of #21.
