### ISSUE TITLE
Proposal: rename @custom annotation to @custom-section

### ISSUE THREAD

**Issue by syrusakbary** [WebAssembly/annotations#10]
> Following up from the discussion here: https://github.com/WebAssembly/wabt/issues/1376

I'd like to propose renaming the syntax for custom sections in wasm from `@custom` to `@custom-section`:

Eg. From:
```wasm
(module
  (@custom "sectionName" (after function) "hello")
  ...
)
```

to:
```wasm
(module
  (@custom-section "sectionName" (after function) "hello")
  ...
)
```

### Why?

After reading [the gist](https://gist.github.com/binji/d1cfff7faaebb2aa4f8b1c995234e5a0) pointed by @binji I thought the `@custom` annotation was referring to just a custom annotation example, not a custom section.

I think a name such as `@custom-section` or `@customSection` might give a bit more context for people that are reading the text format.

**Comment by rossberg** [comment]
It's reasonable, though I don't feel strongly. Anybody else has a thought?

**Comment by binji** [comment]
sgtm. I prefer `@custom-section` to `@customSection`, though.

**Comment by syrusakbary** [comment]
Cool, I can proceed at creating a PR if everyone is ok with it :)

**Comment by rossberg** [comment]
Closing this, since the PR never materialised, and I actually have a slight preference for keeping "custom" – seems more in sync with the existing "func", "memory", etc declarations defining a respective section.
