### ISSUE TITLE
Test assert grammar works, but grammar doesn't fit into current specification

### ISSUE THREAD

**Issue by alexcrichton** [WebAssembly/annotations#6]
Currently there's a test in this repository that the following parses:

```wat
(@a Heiße Würstchen   

)
```

(pulled from [here](https://github.com/WebAssembly/annotations/blob/1a33be6b600698c74797cb8a2b13b01f76316bcd/test/core/annotations.wast#L12-L14))

but according to the current proposed text:

```
annot ::= "(@"idchar+  annotelem* ")"
annotelem ::= keyword | reserved | uN | sN | fN | string | id | "(" annotelem* ")" | "(@"idchar+ annotelem* ")"
```

I don't think any of these can afford for non-ascii characters such as `Heiße`. Is it intended that the spec should be updated or should the test case here be dropped?

**Comment by rossberg** [comment]
Indeed, test was nonsense. Removed.

**Comment by alexcrichton** [comment]
Thanks for the quick fix!
